bot/urls.py
from django.urls import path
from .views import chat 

urlpatterns = [
    path('', chat, name="chat"),
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from user.urls import urlpatterns

urlpatterns = [
    path('', views.college_portal, name='home'),

    path('about/us/', views.about, name='about'),

    path('privacy/', views.privacy, name='privacy'),
    path('termandcondition/', views.terms, name='terms'),

    path('soon/#/', views.soon, name='soon'),


    # Default denied access page if no role is found
    path('denied/', views.denied, name="denied"),

    path('success/', views.success, name="success"),

    path('teacher/student_list', views.student_list, name='student_list'),
    path('export_students/', views.export_students_to_excel, name='export_students'),  # Export to Excel
    
]

portal/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import handler404, handler500

from core.views import custom_404_view, custom_500_view

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

handler404 = custom_404_view
handler500 = custom_500_view

urlpatterns = [
    path('auth/locate/user/admin/', admin.site.urls),
    path('', include('core.urls')),
    path('chat/ai/', include('bot.urls')),
    path('auth/user/', include('user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # path('rest', include('rest_framework.urls')),
    # path('settings/api/secret/', include('base.urls')),

 

user/models.py
from django.db import models
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group
import string
from django.contrib.auth.models import User
import random

class Student(models.Model):
    # Add the student_id field
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student', null=True, blank=True)  # Link student to user
    student_id = models.CharField(max_length=5, unique=True, editable=False, blank=True)

    # Existing fields
    PENDING = 'Pending'
    APPROVED = 'Approved'
    REJECTED = 'Rejected'
    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
    ]

    SEX_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]

    LEARNING_MODE_CHOICES = [
        ('Modular', 'Modular'),
        ('Face to Face', 'Face to Face'),
        ('Online', 'Online'),
        ('Hybrid', 'Hybrid'),
    ]

    STRAND_CHOICES = [
        ('STEM', 'STEM (Science, Technology, Engineering, Mathematics)'),
        ('ABM', 'ABM (Accountancy, Business, and Management)'),
        ('HUMSS', 'HUMSS (Humanities and Social Sciences)'),
        ('GAS', 'GAS (General Academic Strand)'),
        ('TVL', 'TVL (Technical-Vocational-Livelihood)'),
    ]

    TVL_TRACK_CHOICES = [
        ('ICT', 'Information and Communications Technology (ICT)'),
        ('Home Economics', 'Home Economics'),
        ('Tourism', 'Tourism'),
        ('Agri-fishery Arts', 'Agri-fishery Arts (Soon)'),
        ('Industrial Arts', 'Industrial Arts (Soon)'),
        ('Entrepreneurship', 'Entrepreneurship (Soon)'),
    ]

    PAYMENT_METHOD_CHOICES = [
        ('Cash', 'Cash'),
        ('Bank Transfer', 'Bank Transfer'),
        ('Mobile Wallet', 'Mobile Wallet'),
    ]

    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30)
    address = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=50, unique=True)
    phone_validator = RegexValidator(
        regex=r'^(?:\+63|09)\d{9}$',
        message="Phone number must start with '+63' or '09' and be followed by 9 digits."
    )
    phone = models.CharField(validators=[phone_validator], max_length=13, blank=True, null=True)    
    mother_tongue = models.CharField(max_length=30, blank=True)
    religion = models.CharField(max_length=30, blank=True)
    sex = models.CharField(max_length=6, choices=SEX_CHOICES, blank=True)
    learning_mode = models.CharField(max_length=20, choices=LEARNING_MODE_CHOICES, blank=True)
    strand = models.CharField(max_length=20, choices=STRAND_CHOICES, blank=True)
    tvl_track = models.CharField(max_length=30, choices=TVL_TRACK_CHOICES, blank=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, blank=True)
    emergency_contact_name = models.CharField(max_length=50, blank=True)
    emergency_contact_relationship = models.CharField(max_length=20, blank=True)
    emergency_contact_phone = models.CharField(max_length=15, blank=True)
    emergency_contact_email = models.EmailField(blank=True)
    temp_password = models.CharField(max_length=128, blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=PENDING)

    def __str__(self):
        return f"{self.student_id} - {self.first_name} {self.middle_name} {self.last_name} ({self.status})"

    class Meta:
        ordering = ['last_name', 'first_name']
        indexes = [
            models.Index(fields=['student_id']),
            models.Index(fields=['email']),
        ]
        
    def generate_temp_password(self):
        """Generate a random temporary password."""
        length = 8
        characters = string.ascii_letters + string.digits + string.punctuation
        temp_password = ''.join(random.choice(characters) for _ in range(length))
        return temp_password

    def save(self, *args, **kwargs):
        if not self.student_id:
            # Generate a unique student ID
            last_student = Student.objects.order_by('-student_id').first()
            new_id = int(last_student.student_id) + 1 if last_student else 1
            self.student_id = f"{new_id:05d}"

        if self.status == self.APPROVED and not self.temp_password:
            # Generate a temp password if none exists
            self.temp_password = self.generate_temp_password()
            self.send_temp_password_email()

        super().save(*args, **kwargs)

    def create_user(self):
        """Create a User associated with the Student."""
        if not self.user:  # Ensure we only create a User if one doesn't already exist
            user = User.objects.create_user(
                username=self.email,  # Use the email as the username
                email=self.email,
                password=self.temp_password  # Assign the temporary password
            )
            self.user = user  # Ensure this links the user correctly to the student
            self.save()  # Save the student with the associated user
        else:
            print("User already exists for this student.")

    def send_temp_password_email(self):
        """Send an email with the temporary password."""
        try:
            subject = 'Your Temporary Password'
            message = (
                f"Hello {self.first_name},\n\n"
                f"Your email is {self.email},\n\n"
                f"Your temporary password is: {self.temp_password}\n\n"
                f"Please change it after logging in.\n\n"
                "Thank you!"
            )
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])
        except Exception as e:
            print(f"Failed to send email: {e}")  # Consider logging this error in production
        
    # Ensure the Student group exists and assign the user to it
        if self.user:
            student_group, created = Group.objects.get_or_create(name='Student')
            self.user.groups.add(student_group)

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='teacher', blank=True)
    student_id = models.CharField(max_length=5, unique=True, editable=False, blank=True)
    username = models.CharField(max_length=50, editable=False, blank=True, unique=True)
    subject = models.CharField(max_length=50)
    password = models.CharField(max_length=128, blank=True)
    email = models.EmailField(unique=True, blank=True)
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20, blank=True)

    STRANDS = [
        ('STEM', 'STEM'),
        ('ABM', 'ABM'),
        ('HUMSS', 'HUMSS'),
        ('GAS', 'GAS'),
        ('TVL', 'TVL'),
    ]
    teacher_strand = models.CharField(max_length=5, choices=STRANDS)

    TVL_OPTIONS = [
        ('HE - Cookery', 'HE - Cookery'),
        ('HE - Tourism', 'HE - Tourism'),
        ('ICT', 'ICT'),
    ]
    tvl_options = models.CharField(max_length=15, choices=TVL_OPTIONS, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.subject}"

    def save(self, *args, **kwargs):
        # Create or update the related user when saving the teacher instance
        if not self.user:
            # Generate a username if not provided
            if not self.username:
                self.username = self.email

            # Create a User instance
            user = User.objects.create_user(
                username=self.username,
                email=self.email,
                password=self.password if self.password else None,
                first_name=self.first_name,
                last_name=self.last_name
            )
            self.user = user

        # Hash the password if it's provided
        if self.password:
            self.user.set_password(self.password)
            self.user.save()

    # Ensure the Teacher group exists and assign the user to it
        teacher_group, created = Group.objects.get_or_create(name='Teacher')
        self.user.groups.add(teacher_group)
    
        super().save(*args, **kwargs)

class Contact(models.Model):
    name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=50)
    title = models.CharField(max_length=150, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.title}"

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    attachment = models.FileField(upload_to='lesson/attachments/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Event(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    date = models.DateTimeField(blank=True)
    image = models.ImageField(upload_to='events/images/', blank=True, null=True)  # Image field added
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} ({self.date})"

class Resources(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

core/templates/core/about-us.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>
<body class="bg-light">
    {% include 'loader.html' %}
    {% include 'header-general.html' %}

    <header class="bg-gradient text-white text-center py-5 mt-5" style="background: linear-gradient(to right, #007bff, #6610f2);">
        <div class="container">
            <p class="lead text-black">We are committed to excellence in education and student development.</p>
        </div>
    </header>

    <section class="container my-5">
        <h2 class="text-center mb-4">Our Mission</h2>
        <p class="text-center">To provide quality education that empowers students to achieve their dreams and contribute positively to society.</p>

        <div class="row mt-5">
            <div class="col-lg-4 col-md-6 text-center mb-4">
                <div>
                    <i class="fas fa-book-open fa-5x text-primary"></i>
                    <h4 class="mt-3">Quality Education</h4>
                    <p>We strive to offer the best educational programs that cater to the needs of every student.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center mb-4">
                <div>
                    <i class="fas fa-users fa-5x text-primary"></i>
                    <h4 class="mt-3">Community Engagement</h4>
                    <p>Our programs encourage community involvement, fostering a sense of belonging and responsibility.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center mb-4">
                <div>
                    <i class="fas fa-lightbulb fa-5x text-primary"></i>
                    <h4 class="mt-3">Innovative Approaches</h4>
                    <p>We embrace innovation and creativity in our teaching methods to prepare students for the future.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="container my-5">
        <h2 class="text-center mb-4">Meet Our Team</h2>
        <div class="row">
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card text-center">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRST8pvXaSlYob-KqLWH80g_Foj3xBAacgmJQ&s" class="card-img-top rounded-circle mx-auto lazyload" alt="Soon" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">No data</h5>
                        <p class="card-text">Marketing</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card text-center">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRST8pvXaSlYob-KqLWH80g_Foj3xBAacgmJQ&s" class="card-img-top rounded-circle mx-auto lazyload" alt="Soon" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">No Data</h5>
                        <p class="card-text">Director of Operations</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card text-center">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRST8pvXaSlYob-KqLWH80g_Foj3xBAacgmJQ&s" class="card-img-top rounded-circle mx-auto lazyload" alt="Soon" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">No Data</h5>
                        <p class="card-text">Head of Education</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% include 'footer.html' %}
</body>
</html>

core/templates/core/denied.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
    <style>
        body {
            background-color: #f8d7da; /* Light red background */
        }
        .container {
            margin-top: 100px;
            text-align: center;
        }
        .alert {
            background-color: #f5c6cb; /* Light red alert */
            border-color: #f5c6cb; /* Match border color */
        }
    </style>
</head>
<body>
    {% include 'loader.html' %}

    <div class="container">
        <div class="alert alert-danger" role="alert">
            <h1 class="display-4">Access Denied</h1>
            <p class="lead">We're sorry, but you do not have permission to access this page.</p>
            <hr>
            <p>Please contact your administrator if you believe this is an error.</p>
            <a href="{% url 'home' %}" class="btn btn-primary">Go to Home</a>
        </div>
    </div>

</body>
</html>

core/templates/core/privacy_policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>
<body>
    {% include 'loader.html' %}

    {% include 'header-general.html' %}


<div class="container mt-5 mb-5">
    <h1 class="text-center">Privacy Policy</h1>
    <p class="text-center">Effective Date: {{ year }}</p>

    <div class="my-4">
        <h2><i class="fas fa-shield-alt"></i> Introduction</h2>
        <p>At {{ school }}, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website [Insert Website URL], use our services, or engage with us in any other way. Please read this policy carefully.</p>
    </div>

    <div class="my-4">
        <h2><i class="fas fa-info-circle"></i> Information We Collect</h2>
        <h3>Personal Information</h3>
        <p>When you register on our site, we may collect personal information such as your name, email address, phone number, and any other information you provide.</p>
        <h3>Usage Data</h3>
        <p>We may also collect information on how the service is accessed and used. This usage data may include information about your device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.</p>
    </div>

    <div class="my-4">
        <h2><i class="fas fa-lock"></i> How We Use Your Information</h2>
        <p>We use the information we collect in various ways, including to:</p>
        <ul>
            <li>Provide, operate, and maintain our website</li>
            <li>Improve, personalize, and expand our website</li>
            <li>Understand and analyze how you use our website</li>
            <li>Develop new products, services, features, and functionality</li>
            <li>Communicate with you for customer service and marketing purposes</li>
            <li>Process your transactions and send you confirmation</li>
            <li>Find and prevent fraud</li>
        </ul>
    </div>

    <div class="my-4">
        <h2><i class="fas fa-exclamation-triangle"></i> Disclosure of Your Information</h2>
        <p>We may share your information in the following situations:</p>
        <ul>
            <li>By Law or to Protect Rights</li>
            <li>Business Transfers</li>
            <li>Third-Party Service Providers</li>
        </ul>
    </div>

    <div class="my-4">
        <h2><i class="fas fa-user-shield"></i> Security of Your Information</h2>
        <p>The security of your personal information is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.</p>
    </div>

    <div class="my-4">
        <h2><i class="fas fa-question-circle"></i> Changes to This Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    </div>
</div>

{% include 'footer.html' %}

</body>
</html>

core/templates/core/soon.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>
<body class="bg-light">
    {% include 'loader.html' %}

    <div class="container">
        <a href="/" class="btn btn-block btn-danger btn-lg mt-5">Back</a>
    </div>

    <header class="bg-gradient text-white text-center py-5" style="background: linear-gradient(to right, #007bff, #6610f2);">
        <div class="container">
            <h1 class="text-black display-4">Coming Soon!</h1>
            <p class="text-black lead">We're working hard to get our website ready for you.</p>
            <i class="text-black fas fa-tools fa-5x mb-4"></i>
        </div>
    </header>

    <hr class="container">

    <section class="container text-center my-5">
        <h2>Stay Tuned!</h2>
        <p>We appreciate your patience while we prepare for our launch.</p>
        <i class="far fa-clock fa-5x mb-4"></i>
        <p>Subscribe to get notified when we launch!</p>
        <form class="form-inline justify-content-center mt-3">
            <input type="email" class="form-control mr-2" placeholder="Your Email" required>
            <button type="submit" class="btn btn-primary mt-5 btn-lg">Notify Me</button>
        </form>
    </section>

    {% include 'footer.html' %}
</body>
</html>

core/templates/core/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
    <title>{{ page_title }}</title>
</head>
<body>
    {% include 'loader.html' %}
    {% include 'header-general.html' %}
    
    <div class="container my-5">

        <!-- Display student data in a table -->
        {% if students %}
        <table class="table table-bordered table-hover mt-4">
            <thead class="bg-danger text-white">
                <tr>
                    <th>Student ID</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Strand</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ student.student_id }}</td>
                    <td>{{ student.first_name }} {{ student.last_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.phone }}</td>
                    <td>{{ student.get_strand_display }}</td>
                    <td>{{ student.get_status_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="alert alert-warning text-center" role="alert">
            No students available.
        </div>
        {% endif %}
    </div>

    <div class="text-center my-4">
        <a href="{% url 'export_students' %}" class="btn-lg btn btn-success">
            <i class="fas fa-download"></i> Export to Excel
        </a>
    </div>
</body>
</html>

core/templates/core/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background: white;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #4CAF50;
        }
        p {
            font-size: 18px;
            line-height: 1.6;
        }
        a.homeButton {
            display: inline-block;
            margin-top: 30px;
            padding: 10px 15px;
            background: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        a.homeButton:hover {
            background: #45a049;
        }
        a.contactButton {
            display: inline-block;
            color: red;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    {% include 'loader.html' %}

<div class="container">
    <h1>Enrollment Successful!</h1>
    <p>Congratulations! You have been successfully enrolled in IIH College.</p>
    <p>Your details have been recorded, and you will soon receive an email with your username and password for your account.</p>
    <p>Please be patient as we process your enrollment. If you have any questions, feel free to 
    <a target="_blank" class="contactButton" href="mailto:?subject=IIH%20College%20contact&cc=iihc@test.com&bcc=iihcmain.branch@gmail.com&body=Add%20your%20concern%20here">Contact Us</a>.</p>

    <h2>Requirements for New Students & Transferees:</h2>
    <p>
        ✅ NSO/PSA/LIVE BIRTH (Original) <br>
        ✅ Good Moral Certificate (Original) <br>
        ✅ Report Card Grade 10 (to follow) <br>
        ✅ ALS Certificate (if ALS PASSER) <br>
        ✅ ID (Picture Taking agad, kaya ready to pose dapat!)
    </p>    
    <a href="{% url 'home' %}" class="homeButton">Return to Home</a>
</div>

</body>
</html>

core/templates/core/terms_of_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>

<body>
    {% include 'loader.html' %}

    {% include 'header-general.html' %}

<div class="container mt-5 mb-5">
    <h1 class="text-center mb-4">Terms of Service</h1>
    <p class="text-center">Effective Date: {{ year }}</p>

    <div class="mb-4">
        <h2><i class="fas fa-check-circle"></i> 1. Acceptance of Terms</h2>
        <p>By accessing or using our services, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-pencil-alt"></i> 2. Changes to Terms</h2>
        <p>We reserve the right to modify these Terms of Service at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the service after any changes constitutes your acceptance of the new Terms.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-user-shield"></i> 3. User Responsibilities</h2>
        <p>You agree to use the service only for lawful purposes and in accordance with these Terms. You are responsible for ensuring that your use of the service complies with all applicable laws and regulations.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-gavel"></i> 4. Intellectual Property</h2>
        <p>All content, trademarks, and other intellectual property on our website are the property of {{ school }} or our licensors. You may not reproduce, distribute, or create derivative works from any of the content without our express written permission.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-exclamation-triangle"></i> 5. Limitation of Liability</h2>
        <p>In no event shall {{ school }} be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in connection with your use of the service.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-balance-scale"></i> 6. Governing Law</h2>
        <p>These Terms of Service shall be governed by and construed in accordance with the laws of Caloocan City, Philippines.</p>
    </div>

    <div class="mb-4">
        <h2><i class="fas fa-envelope"></i> 7. Contact Information</h2>
        <p>If you have any questions about these Terms of Service, please contact us at:</p>
    </div>
</div>

{% include 'footer.html' %}

</body>
</html>